name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Flutter SDK'yı kurar
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ' 3.22.3'

      # Bağımlılıkları yükler
      - name: Install dependencies
        run: flutter pub get

      # Kod formatını kontrol eder (isteğe bağlı)
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      # Kodun analizini yapar
      - name: Analyze project source
        run: flutter analyze

      # Testleri çalıştırır
      - name: Run tests
        run: flutter test
